default-storage-provider: fs
local-storage-prefix: $SCRATCH/arguelles_delgado_lab/Everyone/$USER/

restart-times: 1
cores: 8
jobs: 10
latency-wait: 120 
keep-going: True
rerun-incomplete: True
printshellcmds: True
use-conda: True
conda-frontend: mamba
use-singularity: True
singularity-args: "--bind /etc/slurm:/etc/slurm /scratch:/scratch"
 #Use this to pass arguments to singularity when running

executor: slurm
default-resources: 
  - slurm_account="arguelles_delgado_lab"
  - slurm_partition=shared
  - mem_mb=10000
  - runtime=60 # minutes